name: Windows

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build_windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        architecture: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build
        working-directory: build
        shell: cmd
        run: |
          ninja

      - name: Test
        working-directory: build
        run: |
          ctest
